title: Retama studio
baseurl: /
permalink: '/:title/'
collections:
  posts:
    permalink: '/posts/:title/'
favicon: images/Logo círculo azul.png
logo_dark: images/Logo círculo azul.png
logo_light: images/Logo círculo azul.png
hamburger_background_image: /images/leaf-light-grey.svg
bg_image_primary: /images/header.jpg
bg_image_primary_opacity: 60
bg_image_secondary: /images/leaf-light-grey.svg
bg_image_product: /images/leaf.svg
snipcart_api_key: ''
footer_text: Copyright 2021. Retama studio. Todos los derechos reservados
palette: green
main_menu:
  - title: Tienda
    url: /store
    style: link
  - title: Sobre nosotros
    url: /about
    style: link
  - title: FAQ
    url: /faq
    style: link
sass:
  style: nested
  precision: 10
plugins:
  - jekyll-menus
exclude:
  - Gemfile
  - Gemfile.lock
  - node_modules
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/
  - LICENSE.md
  - README.md
  - netlify.toml
  - stackbit-build.sh
  - stackbit-pull.js
domain: 'https://retamastudio.com'
